# Generated by Django 4.0.5 on 2022-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='files',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='length',
        ),
        migrations.RemoveField(
            model_name='film',
            name='score',
        ),
        migrations.RemoveField(
            model_name='film',
            name='title',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='End_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='film',
            name='activity_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='film',
            name='bid_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='film',
            name='bid_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='film',
            name='last_date_of_clarifications',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
