# Generated by Django 4.0.5 on 2022-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_files_remove_film_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='bid_file',
            new_name='bid_documnts',
        ),
        migrations.AddField(
            model_name='film',
            name='bid_information',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
