# Generated by Django 4.0.5 on 2022-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_bid_file_film_bid_documnts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='bid_information',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
