# Generated by Django 4.0.5 on 2022-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_bid_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AlterField(
            model_name='film',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
