# Generated by Django 4.0.5 on 2022-08-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_film_id_alter_film_reference_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='BID',
        ),
    ]
